[build]
  command = "npm run build"  # Use "yarn build" if you're using Yarn
  publish = ".next"

[build.environment]
  NODE_VERSION = "16"  # Ensure you're using the correct Node.js version

[build]
  # This sets up Netlify to use the functions in the `netlify/functions` directory
  functions = "netlify/functions"

[context.production.environment]
  # Optional: Add environment variables here


[build]
  command = "npm run build" # Use "yarn build" if you are using Yarn
  publish = "build" # If you are using a build directory, adjust accordingly

[build.environment]
  NODE_VERSION = "16"  # Ensure you're using the correct Node.js version

[functions]
  directory = "netlify/functions" # Adjust if your functions directory is different

[context.production.environment]
  PORT = "3001"
  MONGODB_URI=mongodb://localhost:27017/todoapp?authSource=admin
  JWT_SECRET=random@06
  MONGO_USER=admin
  MONGO_PASSWORD=Nayak@06
